Repository sad-cow-png/Shared-Spaces, pull requests merged in 2021-05, with the labels that each got.

#63 Feature/search result tags
  sadcowpng/sharedspaces/templates/sharedspaces/search_header.html
  sadcowpng/sharedspaces/templates/sharedspaces/search_results.html
  sadcowpng/sharedspaces/templates/sharedspaces/tagged_spaces.html
  sadcowpng/sharedspaces/views.py
Labels: Client Stories

#64 Feature/date decorator
  README.md
  sadcowpng/sharedspaces/decorators.py
  sadcowpng/sharedspaces/forms.py
  sadcowpng/sharedspaces/models.py
  sadcowpng/sharedspaces/tests.py
  sadcowpng/sharedspaces/views.py
Labels: Dev Stories

#65 Feature/client reserved listings
  README.md
  sadcowpng/sharedspaces/static/account.css
  sadcowpng/sharedspaces/templates/sharedspaces/account.html
  sadcowpng/sharedspaces/tests.py
Labels: Client Stories, Epic-Account-Page

#67 Feature/search result tags
  README.md
  sadcowpng/sharedspaces/templates/sharedspaces/search_results.html
  sadcowpng/sharedspaces/tests.py
Labels: Client Stories

#69 Feature/mobile desktop
  sadcowpng/sharedspaces/static/account.css
  sadcowpng/sharedspaces/static/header.css
  sadcowpng/sharedspaces/static/main_pages.css
  sadcowpng/sharedspaces/static/map.css
  sadcowpng/sharedspaces/static/spaces.css
  sadcowpng/sharedspaces/templates/sharedspaces/account_header.html
  sadcowpng/sharedspaces/templates/sharedspaces/client_sign_up.html
  sadcowpng/sharedspaces/templates/sharedspaces/form_header.html
  sadcowpng/sharedspaces/templates/sharedspaces/login.html
  sadcowpng/sharedspaces/templates/sharedspaces/logout.html
  sadcowpng/sharedspaces/templates/sharedspaces/proprietor_signup.html
  sadcowpng/sharedspaces/templates/sharedspaces/reserve_space.html
  sadcowpng/sharedspaces/templates/sharedspaces/signup.html
  sadcowpng/sharedspaces/templates/sharedspaces/tagged_spaces.html
Labels: Dev Stories

#71 Feature/map expansion
  sadcowpng/sharedspaces/static/javascript/mapsFunction.js
  sadcowpng/sharedspaces/templates/sharedspaces/index.html
  sadcowpng/sharedspaces/views.py
Labels: Epic-Map
